all:
	gcc -c hw0401.c 
	gcc -c myfunc.c 
	gcc myfunc.o hw0401.o -lm -o hw0401

#gcc -c mine.c
#gcc -c hw0402.c
#gcc hw0402.o mine.o -lm -o hw0402

	gcc hw0403.c -o hw0403

	gcc hw0405.c -o hw0405
#gcc -c hw0402.c
#gcc hw0402.o mine.c -lm -o hw0402
clean:
	rm -rf *~
#rm -rf *.o *.hw0401

